### ISSUE TITLE
TCP receiving hangs due to CPU-hogging wait loops

### ISSUE THREAD

**Issue by gwideman** [rossmann-engineering/EasyModbusTCP.PY#10]
Running easymodbustcp with Python 3.8.9 on Windows 10-64 Pro (which might make a difference around threading) on a well equipped 4-core PC

I am trying to use Modbus over TCP.

I found that mbclient.write_multiple_registers hangs apparently because it fails to receive a response from the slave. It hangs in:
```
            self.__receivedata = bytearray()
            try:
                while len(self.__receivedata) == 0:
                    pass

```
This kind of loop basically runs the CPU at 100% (at least one of the CPUs or cores) and is the classic bad approach to waiting. But in this case I suspected that it was pre-empting the thread that's supposed to be listening to incoming data.  This same "while...pass" code appears in numerous locations.

So I changed the code to:
```
import time
SHORT_THREAD_WAIT = 0.001
...

            self.__receivedata = bytearray()
            try:
                while len(self.__receivedata) == 0:
                    time.sleep(SHORT_THREAD_WAIT) 
```
This executes a 1 millisec sleep on each loop, and allows the other thread more time to get something done.  It allows communication to succeed, though I don't claim it is optimal or bulletproof.  Among other things, I'm not too confident that this code avoids seeing an only-partly-loaded version of __receivedata, as it's not clear (to me) what parts of this process are atomic, and there's no obvious mutex.  Something to consider.

**Comment by rossmann-engineering** [comment]
Added in new version
