### ISSUE TITLE
1.4.0 is not working but 1.2.4 is ok

### ISSUE THREAD

**Issue by racuca** [rossmann-engineering/EasyModbusTCP.PY#11]
Hi. 
I notice my problem.

Environments :
Raspberry Pi 4B, 
latest desktop buster image, 
python 3.7.3 virtual environment 
easymodbus

trying to call read input registers...
1.4.0 version is not working. raised function_codeNotSupportedException 
but 1.2.4 is working fine.

let me know any suggestions or checking point.

**Comment by rossmann-engineering** [comment]
Function code not supported is a response from your server
