### ISSUE TITLE
'pip install EasyModbus' installs wrong Version

### ISSUE THREAD

**Issue by matthias1962** [rossmann-engineering/EasyModbusTCP.PY#12]
I did a 'pip install EasyModus' just like mentioned in the documentation.
The iInstalltion is successfull: 'EasyModbus in ./.venv/lib/python3.9/site-packages (1.4.0)'

But when I take a look at the sources, the are diffent from these in this repository.
For example in the installed files the helper function 'def convert_registers_to_double(registers):' has only one argument.
But that should be 'def convert_registers_to_float(registers, register_order=RegisterOrder.lowHigh):' with two arguments.

**Comment by rossmann-engineering** [comment]
Updated latest version in Pypi
