### ISSUE TITLE
method write_multiple_registers creates invalid modbus query

### ISSUE THREAD

**Issue by Teubex** [rossmann-engineering/EasyModbusTCP.PY#3]
As I started working with the easymodbus library for python3 I encountered an error, which occured to me while using the "write_multiple_registers" method.

My master was controlling a slave, which took its instructions from the ascii-values the master submitted into a number of registers, starting from register 0.

As my slave did not seem to respond to my masters  commands, I checked the Modbus TCP/IP - message via Wireshark and found that the length of my package was wrong, as you can see in this picture:
![picture1](https://user-images.githubusercontent.com/55445373/65046870-b26c2e00-d961-11e9-908c-ba444cebd63c.png)

To adjust my messages length parameter, I changed a few lines in the methods code:
line 741:
length = len(values)*2+7
instead of length = 6

line 791:
length_lsb = length&0xFF;
instead of length_lsb = 0x06;

line 792:
length_msb = (length&0xFF00) >> 8
instead of length_msb = 0x00

As you can see in my second picture, it fixed the issue for me.
![picture2](https://user-images.githubusercontent.com/55445373/65046869-b26c2e00-d961-11e9-8350-461afadb1426.png)
Nonetheless I would love to see your take on this problem.

Kind regards, Alex

**Comment by rossmann-engineering** [comment]
Finally fixed
