### ISSUE TITLE
read_discreteinputs 

### ISSUE THREAD

**Issue by benjipotter** [rossmann-engineering/EasyModbusTCP.PY#7]
Using 1.4.0 from pip and following instructions for read_discreteinputs, providing the range e.g. (0, 8) results in error "TypeError: hex() takes no arguments (1 given)". Previously I have been using an old version 12.09.2016 and this worked fine. Your older example on http://easymodbustcp.net/en/python-codesamples also does not work. Love to update to the latest version, and thank you for your efforts!

**Comment by rossmann-engineering** [comment]
I think you used Python version < 3.8. I changed the documentation accordingly.
