### ISSUE TITLE
Contrary to doc, easymodbus cannot be used with Python <3.8

### ISSUE THREAD

**Issue by gwideman** [rossmann-engineering/EasyModbusTCP.PY#8]
There are statements in modbusClient.py that call bytearray.hex(' '). But bytearray.hex with an argument was only introduced in Python 3.8. So that code fails.
It happens to be in logging.debug statements, so perhaps those were supposed to be removed?

**Comment by rossmann-engineering** [comment]
Updated the documentation accordingly
